### ISSUE TITLE
https

### ISSUE THREAD

**Issue by elof** [Macrometacorp/tutorial-addressbook-restql#3]
The live demo app needs to be hosted behind a cdn (using Github pages makes sense to me) and https need to be enforced

**Comment by yyovkov** [comment]
GitHub pages enabled for the repository https://github.com/Macrometacorp/tutorial-addressbook-restql.

**Comment by diana-macrometa** [comment]
What's the status on this issue?

**Comment by astrotars** [comment]
@diana-macrometa looks like it's live on https://macrometacorp.github.io/tutorial-addressbook-restql/

**Comment by diana-macrometa** [comment]
Closing.
